#
# Installs Redis
#

---

- name: 'remove old brew-installed redis from launchctl (ignore error because it may not be there)'
  command: 'launchctl remove homebrew.mxcl.redis'
  ignore_errors: true

- name: 'remove old brew-installed redis launchctl plist'
  file:
    path: '~/Library/LaunchAgents/homebrew.mxcl.redis.plist'
    state: 'absent'

- name: 'install redis'
  homebrew:
    name: 'redis'
    state: 'latest'
    update_homebrew: true

- name: 'configure redis'
  copy:
    dest: '/usr/local/etc/redis.conf'
    src: 'redis.conf'

- name: '~/Library/LaunchAgents exists'
  file:
    path: '~/Library/LaunchAgents'
    state: 'directory'

- name: 'link brew-installed redis into ~/Library/LaunchAgents'
  file:
    dest: '~/Library/LaunchAgents/homebrew.mxcl.redis.plist'
    src: '/usr/local/opt/redis/homebrew.mxcl.redis.plist'
    state: 'link'

- name: 'start redis'
  command: 'launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist'
