# Installs a Mac app by downloading a DMG from specified URL, mounting the DMG, and copying
# any contained apps to /Applications.
#
#  dmg_url: URL to download
#  dmg_tmp_filename: temp file to download to
#  dmg_mount_path: /Volumes absolute path to mount the temp file to (needn't be similar to dmg_tmp_filename)
#
#  TODO: dmg_tmp_filename & dmg_mount_path may as well be removed; we could generate random filename & /Volumes path

---

- name: 'installing an app by downloading .dmg, mounting, then copying'
  debug:
    msg: '{{ dmg_url }}'

- name: 'create download tmp directory'
  file:
    path: '/.ansible-downloads'
    state: 'directory'

- name: 'download dmg'
  get_url:
    dest: '/.ansible-downloads/{{ dmg_tmp_filename }}'
    url: '{{ dmg_url }}'

- name: 'mount dmg'
  command: 'hdiutil attach -mountpoint {{ dmg_mount_path }} {{ dmg_tmp_filename }}'
  args:
    chdir: '/.ansible-downloads'

- name: 'copy whatever *.app(s) the dmg contains to /Applications'
  shell: 'cp -R {{ dmg_mount_path}}/*.app /Applications'

- name: 'unmounting dmg'
  command: 'hdiutil detach {{ dmg_mount_path }}'

- name: 'delete download tmp directory'
  file:
    path: '/.ansible-downloads'
    state: 'absent'
