---

- include: '../../dev-common/tasks/brew.yml'

# Homebrew
- homebrew_tap:
    tap: '{{ item }}'
  with_items: '{{ homebrew_taps }}'
  tags: brew

- homebrew:
    name: git
    state: latest
    update_homebrew: yes
  tags: brew

- homebrew:
    name: '{{ homebrew_packages }}'
    state: latest
  tags: brew

- homebrew_cask:
    name: '{{ item }}'
    state: installed
  with_items: '{{ homebrew_cask_packages }}'
  tags: brew

- name: 'copy apps from cask to /Applications (copy for idempotency as cask does not expect files to have moved)'
  shell: 'find /usr/local/Caskroom/ -name "*.app" -not -path "*/Contents/*" -exec cp -f {} /Applications ";"'
  become: true

- name: Install TypeScript node.js package.
  npm:
    name: typescript

- name: Install "systemjs" node.js package on version 0.21.5.
  npm:
    name: systemjs
    version: '0.21.5'

-name: Install MochaJS testing framework
  npm:
    name: mocha