---

- include: '../../dev-common/tasks/brew.yml'

- name: 'install user applications with cask'
  homebrew_cask:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'appcleaner'
    - 'google-chrome'
    - 'firefox'
    - 'dropbox'
    - 'intellij-idea'
    - 'sequel-pro'
    - 'slack'
    - 'superduper'
    - 'adobe-reader'
    - 'virtualbox'
    - 'sourcetree'
  ignore_errors: true

- name: 'copy apps from cask to /Applications (copy for idempotency as cask does not expect files to have moved)'
  shell: 'find /usr/local/Caskroom/ -name "*.app" -not -path "*/Contents/*" -exec cp -f {} /Applications ";"'
  become: true
