# Provision latest Java

---

- include: 'brew.yml'

- name: 'ensure Java is installed w/ cask. If you want a new revision first run: brew cask reinstall java (homebrew_cask module does not upgrade/reinstall) then rerun'
  homebrew_cask:
    name: 'java'
    state: 'present'

- name: 'Remove any potentially conflicting JAVA_HOME in .profile'
  lineinfile:
    create: true
    dest: '/Users/{{ ansible_user_id }}/.profile'
    regexp: 'JAVA_HOME'
    state: 'absent'

- name: 'So JAVA_HOME is available on command line & in IntelliJ, add to .profile'
  lineinfile:
    create: true
    dest: '/Users/{{ ansible_user_id }}/.profile'
    line: 'export JAVA_HOME=`/usr/libexec/java_home`'
    state: 'present'