# Provision Sublime
---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install sublime text 3
  homebrew_cask: name=sublime-text state=present

- name: create directories
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
  with_items:
    - ~/Library/Application Support/Sublime Text 3
    - ~/Library/Application Support/Sublime Text 3/Packages
    - ~/Library/Application Support/Sublime Text 3/Packages/User
    - ~/Library/Application Support/Sublime Text 3/Installed Packages

- name: download package control
  get_url:
    url: "http://sublime.wbond.net/Package%20Control.sublime-package"
    dest: "~/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package"

- name: get and update all sublime plugins
  git: update=yes version="{{item.version|default('master')}}" repo="{{item.repo}}" dest="~/Library/Application Support/Sublime Text 3/Packages/{{item.dest}}"
  with_items: "{{ sublime_packages }}"

- name: render the sublime config file
  template: src=config.j2 dest="~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"

- name: 'Create a symlink for sublime'
  command: ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl arg1
  args:
    creates: /usr/local/bin/sublime

- name: 'Add path to .profile'
  lineinfile:
    create: true
    dest: '/Users/{{ ansible_user_id }}/.profile'
    line: 'export PATH=/bin:/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:$PATH'
    state: 'present'

- name: 'Add editor path to .profile'
  lineinfile:
    create: true
    dest: '/Users/{{ ansible_user_id }}/.profile'
    line: export EDITOR='subl -w'
    state: 'present'

- name: 'Reload bash_profile'
  sudo: no   
  shell: . /users/{{ ansible_user_id }}/.bash_profile

- name: 'Set git text editor'
  command: git config --global core.editor sublime